# Custom PDB checker deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdb-checker
  namespace: k8sgpt-operator-system
  labels:
    app: pdb-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdb-checker
  template:
    metadata:
      labels:
        app: pdb-checker
    spec:
      serviceAccountName: pdb-checker
      containers:
      - name: pdb-checker
        image: alpine/k8s:1.28.0
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Checking for missing PDBs..."
            
            # Get all deployments with multiple replicas
            kubectl get deployments --all-namespaces -o json | \
            jq -r '.items[] | select(.spec.replicas > 1) | "\(.metadata.namespace)/\(.metadata.name)"' | \
            while read dep; do
              namespace=$(echo $dep | cut -d'/' -f1)
              name=$(echo $dep | cut -d'/' -f2)
              
              # Check if PDB exists for this deployment
              if ! kubectl get pdb -n $namespace --selector="app=$name" -o name >/dev/null 2>&1; then
                echo "ALERT: Missing PDB for deployment $name in namespace $namespace"
                
                # Create a Kubernetes event for K8sGPT to detect
                kubectl annotate deployment $name -n $namespace \
                  k8sgpt.ai/missing-pdb="true" \
                  k8sgpt.ai/pdb-recommendation="Create PodDisruptionBudget for high availability" \
                  --overwrite=true
              fi
            done
            
            sleep 300  # Check every 5 minutes
          done
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# ServiceAccount for PDB checker
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdb-checker
  namespace: k8sgpt-operator-system
---
# ClusterRole for reading deployments and PDBs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pdb-checker
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pdb-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pdb-checker
subjects:
- kind: ServiceAccount
  name: pdb-checker
  namespace: k8sgpt-operator-system